### PR TITLE
Add inline

### LINKED ISSUE #17: webpack_entry_css inline
Can we generate inline_css instead of link tag?
This is useful in twig blocks were link tags inside body tag is not a good practice. See the [Specification](https://www.w3.org/TR/html401/struct/links.html#edef-LINK).

There is good Extention in TWIG [ twigphp/cssinliner-extra](https://github.com/twigphp/cssinliner-extra) but it does not work with your Extension.

### PR DESCRIPTION
**Pull request by fullpipe**
Add `inline` token.
Fix major bug with  `public_path_*` extention parameter. Now it works as ecpected.

### CODE REVIEW

**Comment by raoulclais** [comment]
Hi, what still remains to be done in order to merge this PR ?

**Comment by fullpipe** [comment]
@raoulclais hello! I just forgot about it )
Thank you for remind. I'll try to complete it next weekend. 

As I remember it has breaking changes, so it will be major release

**Comment by raoulclais** [comment]
I would love to see a new release with it.

Thank you very much for your work.

**Comment by fullpipe** [comment]
@raoulclais could you try out this branch? Extension params were changed.  
See https://github.com/fullpipe/twig-webpack-extension/tree/add-inline#register-as-a-twig-extension

**Comment by raoulclais** [comment]
I will try it today

**Comment by raoulclais** [comment]
It seems good to me !

**Comment by raoulclais** [comment]
This PR should close issue #17

**Comment by raoulclais** [comment]
Thank you !

**Pull request merged**
